# Generated by Django 5.0.6 on 2024-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
